name: e_explore
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter


#  http
#  intl


  cupertino_icons: ^1.0.8
  # state management
  get: ^4.7.1

  # emulator
  device_preview: ^1.2.0
  http: ^1.3.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


# LOCAL FONTS  #
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_fonts/Raleway-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/raleway_fonts/Raleway-VariableFont_wght.ttf
        - asset: assets/fonts/raleway_fonts/static/Raleway-Black.ttf
        - asset: assets/fonts/raleway_fonts/static/Raleway-BlackItalic.ttf
        - asset: assets/fonts/raleway_fonts/static/Raleway-Bold.ttf
        - asset: assets/fonts/raleway_fonts/static/Raleway-ExtraBold.ttf
        - asset: assets/fonts/raleway_fonts/static/Raleway-ExtraBoldItalic.ttf

    - family: Oleo
      fonts:
        - asset: assets/fonts/oleo_fonts/OleoScript-Bold.ttf
        - asset: assets/fonts/oleo_fonts/OleoScript-Regular.ttf


































